package lake

import (
	"context"
	"fmt"
	"strings"

	"github.com/hkloudou/lake/v3/internal/index"
	"github.com/hkloudou/lake/v3/internal/utils"
)

// WriteRequest represents a write request
type WriteRequest struct {
	Catalog   string    // Catalog name
	Path      string    // JSON path (e.g., "/user/profile/name"); "/" means root
	Body      []byte    // JSON body to write (raw bytes from network)
	MergeType MergeType // Merge strategy (Replace, RFC7396, or RFC6902)
}

// Write writes data to the catalog. Timestamp and sequence ID are auto-generated by Redis.
//
// Merge Types:
//   - MergeTypeReplace (1): Simple field replacement
//   - MergeTypeRFC7396 (2): RFC 7396 JSON Merge Patch (field-level or root-level)
//   - MergeTypeRFC6902 (3): RFC 6902 JSON Patch (field-level or root-level)
//
// Path:
//   - For Replace/RFC7396: target field ("/" means whole document)
//   - For RFC6902: scope of operations ("/" means root)
//
// Body: raw JSON bytes from network. Examples:
//   - String:  []byte(`"Alice"`)
//   - Number:  []byte(`30`)
//   - Object:  []byte(`{"age":30}`)
//   - RFC7396: []byte(`{"age":31,"city":null}`)
//   - RFC6902: []byte(`[{"op":"add","path":"/a","value":1}]`)
//
// DESIGN DECISION — orphan storage objects are accepted (intentional):
//
// The two-phase commit is:
//   1. ZADD pending|...           (atomic in Redis)
//   2. storage.Put(deltaKey, body) (slow, may fail or process may crash)
//   3. ZADD delta|... + ZREM pending|... (atomic in Redis)
//
// Any failure between step 2 and step 3 (network blip, process kill,
// pending↔committed member mismatch, etc.) leaves the storage object
// behind without a committed Redis index entry — an orphan.
//
// This is the explicit contract, not a bug:
//   - The pending member at step 1 ages out after 120s and reader.go
//     filters it out, so reads stay consistent.
//   - ClearHistory is the unified reaper for orphan storage objects.
//   - The disk waste in transient failure modes is negligibly small and
//     acceptable in exchange for the simpler, lock-free write path.
//
// A future optimization (write-buffer + atomic rename, similar to
// fsync-on-rename pattern) could eliminate orphans, but is intentionally
// out of scope for v3.
func (c *Client) Write(ctx context.Context, req WriteRequest) error {
	c.emitEvent(req.Catalog, "Write", map[string]any{"path": req.Path, "mergeType": int(req.MergeType)})

	if err := utils.ValidateFieldPath(req.Path); err != nil {
		return err
	}

	if err := c.ensureInitialized(ctx); err != nil {
		return err
	}

	// Step 1: Atomically get TimeSeqID and pre-commit to Redis (pending state)
	tsSeq, pendingMember, err := c.writer.GetTimeSeqIDAndPreCommit(ctx, req.Catalog, req.Path, req.MergeType)
	if err != nil {
		return fmt.Errorf("failed to generate timeseq and precommit: %w", err)
	}

	// Step 2: Write to storage
	if c.storage == nil {
		return fmt.Errorf("storage not initialized")
	}
	storageDeltaKey := c.storage.MakeDeltaKey(req.Catalog, tsSeq, int(req.MergeType))
	if err := c.storage.Put(ctx, storageDeltaKey, req.Body); err != nil {
		// Rollback: remove pending member so Read no longer detects this write.
		c.writer.Rollback(ctx, req.Catalog, pendingMember)
		return fmt.Errorf("failed to write to storage: %w", err)
	}

	// Step 3: Atomically commit (remove pending, add committed)
	committedMember := index.EncodeDeltaMember(req.Path, req.MergeType, tsSeq)
	if strings.TrimPrefix(pendingMember, "pending|") != committedMember {
		return fmt.Errorf("pending member and committed member do not match: %s != %s", pendingMember, committedMember)
	}
	if err := c.writer.Commit(ctx, req.Catalog, pendingMember, committedMember, tsSeq.Score()); err != nil {
		return fmt.Errorf("failed to commit: %w", err)
	}

	return nil
}
